### Register User
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "user",
  "email": "user@example.com",
  "password": "1234567"
}
### Login User
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "1234657"
}
### Get Current User
GET http://localhost:3001/api/auth/me
Authorization: Bearer <token>

### Change Password
PUT http://localhost:3001/api/auth/change-password
Authorization: Bearer <token>
Content-Type: application/json

{
  "oldPassword": "1234657",
  "newPassword": "2222222"
}

### Logout User
POST http://localhost:3001/api/auth/logout  
Authorization: Bearer <token>

### Admin Dashboard
GET http://localhost:3001/api/auth/admin/dashboard
Authorization: Bearer <token>
